# Generated by Django 6.0.8 on 2026-08-21 17:09

import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0001_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x', models.PositiveSmallIntegerField(editable=False)),
                ('y', models.PositiveSmallIntegerField(editable=False)),
                ('name', models.CharField(db_index=True, editable=False, max_length=5)),
                ('state', django_fsm.FSMField(choices=[('PENDING', 'Pending'), ('CLOSED', 'Closed'), ('OPENED', 'Opened')], default='PENDING', max_length=50, protected=True)),
                ('challenge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cell', to='challenges.challenge')),
            ],
            options={
                'verbose_name': 'cell',
                'verbose_name_plural': 'Cells',
            },
        ),
        migrations.CreateModel(
            name='CellAttribute',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attribut', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cell', to='games.specialattribute')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='grid.cell')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rows', models.PositiveSmallIntegerField(default=6)),
                ('columns', models.PositiveSmallIntegerField(default=8)),
                ('empty_cell_count', models.PositiveSmallIntegerField(default=8)),
                ('point_distribution', models.JSONField(default=dict)),
                ('state', django_fsm.FSMField(choices=[('configured', 'Configured'), ('positions_drawn', 'Cells position'), ('attributes_drawn', 'Cells attributes')], default='configured', max_length=50, protected=True)),
                ('episode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grid', to='games.episode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cell',
            name='grid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='grid.grid'),
        ),
        migrations.AddConstraint(
            model_name='cell',
            constraint=models.UniqueConstraint(fields=('grid', 'x', 'y'), name='unique_cell_coordinate_per_grid'),
        ),
        migrations.AddConstraint(
            model_name='cell',
            constraint=models.UniqueConstraint(fields=('grid', 'name'), name='unique_cell_name_per_grid'),
        ),
    ]
