# Generated by Django 6.0.8 on 2026-08-25

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("grid", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="grid",
            name="max_attrs_per_cell",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
