# Generated by Django 6.0.8 on 2026-08-21 17:09

import django.contrib.postgres.fields
import django.core.validators
import django.utils.timezone
import django_fsm
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposals', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField())),
                ('ok_answers', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField())),
                ('access', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=8), blank=True, null=True)),
                ('timespan', models.PositiveIntegerField(default=10, help_text='Time available to send a reply (seconds)', validators=[django.core.validators.MinValueValidator(1)])),
                ('gain', models.PositiveSmallIntegerField(default=0, help_text='Point to gain in case of success')),
                ('ttl', models.DateTimeField(blank=True, null=True)),
                ('state', django_fsm.FSMField(choices=[('pending', 'PENDING'), ('opened', 'OPENED'), ('closed', 'CLOSED')], db_index=True, default='pending', max_length=50, protected=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True)),
            ],
            options={
                'verbose_name': 'challenge',
                'verbose_name_plural': 'Challenges list',
            },
        ),
        migrations.CreateModel(
            name='PlayerResponse',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answers', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), null=True)),
                ('score', models.SmallIntegerField(default=0)),
                ('state', django_fsm.FSMField(choices=[('pending', 'PENDING'), ('submit', 'SUBMIT'), ('outdated', 'OUTDATED'), ('succeeded', 'SUCCEEDED'), ('failed', 'FAILED'), ('skipped', 'SKIPPED')], db_index=True, default='pending', max_length=50, protected=True)),
            ],
            options={
                'verbose_name': 'response',
                'verbose_name_plural': 'Players responses',
            },
        ),
    ]
