# Generated by Django 6.0.8 on 2026-08-21 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0001_initial'),
        ('games', '0001_initial'),
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='games.episode'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='question',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='challenges', to='qa.question'),
        ),
        migrations.AddField(
            model_name='playerresponse',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='challenges.challenge'),
        ),
        migrations.AddField(
            model_name='playerresponse',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='games.participant'),
        ),
    ]
