<script lang="ts">
	import { onMount } from 'svelte';
	import { createQueryConfig, deleteQueryConfig, getEpisode, getQuestions, getQueryConfigs, type Episode, type Question, type QueryConfig } from '$lib/episodes-api';
	import type { PageProps } from './$types';
	let { params }: PageProps = $props(); let episode = $state<Episode | null>(null); let questions = $state<Question[]>([]); let configs = $state<QueryConfig[]>([]); let search = $state(''); let selectedLevel = $state('all'); let tags = $state(''); let mode = $state<'select' | 'unselect'>('select'); let join = $state<'and' | 'or'>('and'); let isLoading = $state(true); let errorMessage = $state('');
	const filteredQuestions = $derived(questions.filter((question) => question.question.toLowerCase().includes(search.toLowerCase()) && (selectedLevel === 'all' || question.level === Number(selectedLevel))));
	async function load() { try { [episode, questions, configs] = await Promise.all([getEpisode(params.id), getQuestions(), getQueryConfigs(params.id)]); } catch (error) { errorMessage = error instanceof Error ? error.message : 'Impossible de charger les questions.'; } finally { isLoading = false; } }
	onMount(() => { void load(); });
	async function addConfig() { try { configs = [...configs, await createQueryConfig(params.id, { mode, join, tags: tags.split(',').map((tag) => tag.trim()).filter(Boolean), level: selectedLevel === 'all' ? [] : [Number(selectedLevel)] })]; tags = ''; } catch (error) { errorMessage = error instanceof Error ? error.message : 'Impossible d’ajouter cette règle.'; } }
	async function removeConfig(id: string) { await deleteQueryConfig(params.id, id); configs = configs.filter((config) => config.id !== id); }
</script>
<main><a href={`/episodes/${params.id}`}>← Retour à l’épisode</a>{#if isLoading}<p>Chargement…</p>{:else if episode}<header><p>Épisode · {episode.title}</p><h1>Questions</h1><span>{questions.length} dans la bibliothèque</span></header><section class="rules"><h2>Règles de sélection</h2><form onsubmit={(event) => { event.preventDefault(); void addConfig(); }}><select bind:value={mode}><option value="select">Inclure</option><option value="unselect">Exclure</option></select><select bind:value={join}><option value="and">ET</option><option value="or">OU</option></select><input bind:value={tags} placeholder="Tags, séparés par des virgules" /><select bind:value={selectedLevel}><option value="all">Tous les niveaux</option>{#each [1,2,3,4,5] as level}<option value={String(level)}>Niveau {level}</option>{/each}</select><button>Ajouter la règle</button></form>{#each configs as config}<p>{config.mode === 'select' ? 'Inclure' : 'Exclure'} · {config.join.toUpperCase()} · {config.tags?.join(', ') || 'tous tags'} · niveaux {config.level?.join(', ') || 'tous'} <button type="button" onclick={() => void removeConfig(config.id)}>Supprimer</button></p>{:else}<p>Ajoutez une règle pour définir les questions utilisables dans cet épisode.</p>{/each}</section>{#if questions.length}<section class="filters"><input bind:value={search} type="search" placeholder="Rechercher une question" /></section><section class="list">{#each filteredQuestions as question}<article><div><strong>{question.question}</strong><small>{question.tags.join(' · ') || 'Sans tag'}</small></div><span>Niveau {question.level}</span><span>{question.is_active ? 'Active' : 'Inactive'}</span></article>{:else}<p class="empty">Aucune question ne correspond à votre recherche.</p>{/each}</section>{:else}<section class="empty"><strong>La bibliothèque de questions est vide.</strong><p>Créez ou importez des questions dans QA pour pouvoir les sélectionner ici.</p></section>{/if}{#if errorMessage}<p class="error" role="alert">{errorMessage}</p>{/if}{:else}<p class="error">{errorMessage}</p>{/if}</main>
<style>:global(*){box-sizing:border-box}:global(html),:global(body){margin:0;background:#0f172a;color:#f8fafc;font-family:Inter,ui-sans-serif,system-ui,sans-serif}main{width:min(100%,72rem);min-height:100dvh;margin:auto;padding:clamp(1.25rem,4vw,3rem)}a{color:#c4b5fd;font-size:.85rem;font-weight:750;text-decoration:none}header{display:flex;align-items:end;gap:1rem;margin:3rem 0 2rem}header p{margin:0 auto 0 0;color:#94a3b8;font-size:.85rem}h1{margin:0;color:#f8fafc;font-size:clamp(2.5rem,6vw,4.5rem);letter-spacing:-.07em}header span{color:#cbd5e1}.filters{display:flex;gap:.7rem;margin-bottom:1rem}.filters input,.filters select{min-height:2.8rem;border:1px solid #475569;border-radius:.55rem;padding:0 .7rem;background:#1e293b;color:#f8fafc;font:inherit}.filters input{flex:1}.list{border:1px solid #334155;border-radius:1rem;overflow:hidden;background:#1e293b}.list article{display:grid;grid-template-columns:minmax(0,1fr) 7rem 5rem;gap:1rem;align-items:center;border-top:1px solid #334155;padding:1rem}.list article:first-child{border-top:0}.list strong,.list small{display:block}.list small{margin-top:.3rem;color:#94a3b8;font-size:.75rem}.list span{color:#cbd5e1;font-size:.8rem}.empty{padding:2rem;color:#94a3b8;text-align:center}.error{color:#fecaca}@media(max-width:600px){header{align-items:flex-start;flex-direction:column}.filters{flex-direction:column}.list article{grid-template-columns:1fr}.list span{color:#94a3b8}}</style>
