# Generated by Django 6.0.8 on 2026-08-21 17:09

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=160, verbose_name='Answer')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'proposition',
                'verbose_name_plural': 'Question Proposition List',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=160, verbose_name='Question')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Wood'), (2, 'Stone'), (3, 'Bronze'), (4, 'Silver'), (5, 'Gold')], default=1, verbose_name='Level')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'List of questions',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='qa_question_tags_gin')],
            },
        ),
        migrations.CreateModel(
            name='AnswerReason',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='justification', to='qa.question')),
            ],
            options={
                'verbose_name': 'justification',
                'verbose_name_plural': 'Question justification',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_correct', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('proposition', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='question_links', to='qa.proposition')),
                ('question', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='qa.question')),
            ],
            options={
                'verbose_name': 'answer',
                'verbose_name_plural': 'Answers List',
                'constraints': [models.UniqueConstraint(fields=('question', 'proposition'), name='qa_unique_question_proposition')],
            },
        ),
    ]
