<script lang="ts">
	import { goto } from '$app/navigation'; import { saveToken } from '$lib/auth';
	type LoginResponse = { token?: string; non_field_errors?: string[]; detail?: string };
	const apiBaseUrl = (import.meta.env.PUBLIC_API_URL ?? '').replace(/\/$/, ''); let username = $state(''); let isSubmitting = $state(false); let errorMessage = $state('');
	async function login() { errorMessage = ''; isSubmitting = true; try { const response = await fetch(`${apiBaseUrl}/api/auth/login/`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username }) }); const payload: LoginResponse = await response.json().catch(() => ({})); if (!response.ok || !payload.token) throw new Error(payload.non_field_errors?.[0] ?? payload.detail ?? 'Connexion impossible.'); saveToken(payload.token); await goto('/'); } catch (error) { errorMessage = error instanceof Error ? error.message : 'La connexion est indisponible.'; } finally { isSubmitting = false; } }
</script>
<svelte:head><title>Connexion joueur · La Grille</title></svelte:head>
<main><section><p class="eyebrow">EpicQuiz — La Grille</p><h1>Joueur</h1><p>Entrez votre nom d’utilisateur pour rejoindre votre partie.</p><form onsubmit={(event) => { event.preventDefault(); login(); }}><label for="username">Nom d’utilisateur</label><input id="username" autocomplete="username" bind:value={username} required />{#if errorMessage}<p class="error" role="alert">{errorMessage}</p>{/if}<button type="submit" disabled={isSubmitting}>{isSubmitting ? 'Connexion…' : 'Se connecter'}</button></form></section></main>
<style>main { display: grid; min-height: 100dvh; place-items: center; padding: 1.5rem; background: #0f172a; } section { width: min(100%, 28rem); padding: clamp(2rem, 7vw, 4rem); border: 1px solid #334155; border-radius: 1rem; background: #17213a; } .eyebrow { color: #c4b5fd; font-size: .75rem; font-weight: 700; letter-spacing: .1em; text-transform: uppercase; } h1 { margin: .4rem 0 1rem; font-size: 2.5rem; letter-spacing: -.05em; } p { color: #cbd5e1; } form { display: grid; gap: .6rem; margin-top: 2rem; } label { font-size: .875rem; font-weight: 650; } input, button { min-height: 2.8rem; border-radius: .5rem; font: inherit; } input { border: 1px solid #475569; padding: 0 .75rem; background: #0f172a; color: #f8fafc; } button { margin-top: .7rem; border: 0; background: #8b5cf6; color: white; font-weight: 700; cursor: pointer; } button:disabled { opacity: .6; cursor: wait; } .error { margin: .25rem 0 0; color: #fca5a5; }</style>
