# Generated by Django 6.0.8 on 2026-08-21 17:09

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('time_slot', models.PositiveSmallIntegerField(default=10, help_text='Base of timespan for current game (seconds)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Default game timespan')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('state', django_fsm.FSMField(choices=[('pending', 'Pending'), ('start', 'Started'), ('end', 'Ended')], default='pending', max_length=50, protected=True)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='SpecialAttribute',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_attributes', to='games.episode')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('PLAYER', 'Player'), ('SCREEN', 'Screen'), ('PRESENTER', 'Presenter'), ('OPERATOR', 'Operator')], db_index=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, help_text='Tags list', null=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='games.episode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_participant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'participant',
                'verbose_name_plural': 'Participants',
            },
        ),
        migrations.CreateModel(
            name='PrizeAttribute',
            fields=[
                ('specialattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='games.specialattribute')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='prizes')),
            ],
            options={
                'abstract': False,
            },
            bases=('games.specialattribute',),
        ),
        migrations.CreateModel(
            name='StealAttribute',
            fields=[
                ('specialattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='games.specialattribute')),
            ],
            options={
                'abstract': False,
            },
            bases=('games.specialattribute',),
        ),
        migrations.CreateModel(
            name='QueryConfig',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('join', models.CharField(choices=[('or', 'OR'), ('and', 'AND')], default='and', max_length=3)),
                ('mode', models.CharField(choices=[('select', 'Select'), ('unselect', 'Unselect')], max_length=8)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, help_text='Tags list', null=True)),
                ('level', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, help_text='Question level', null=True)),
                ('episode', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='queries_config', to='games.episode')),
            ],
            options={
                'verbose_name': 'Query conf',
                'verbose_name_plural': 'Queries conf',
                'ordering': ('id',),
            },
        ),
    ]
