# Generated by Django 6.0.8 on 2026-08-24

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
        ("qa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EpisodeQuestion",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_questions",
                        to="games.episode",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="episode_selections",
                        to="qa.question",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="episodequestion",
            constraint=models.UniqueConstraint(
                fields=("episode", "question"),
                name="unique_question_selection_per_episode",
            ),
        ),
    ]
