<script lang="ts">
	import { onMount } from 'svelte';
	import GridConfigurationDialog from '$lib/GridConfigurationDialog.svelte';
	import { getEpisode, gridLabel, type Episode } from '$lib/episodes-api';
	import type { PageProps } from './$types';
	let { params }: PageProps = $props(); let episode = $state<Episode | null>(null); let isLoading = $state(true); let isEditing = $state(false); let errorMessage = $state('');
	onMount(async () => { try { episode = await getEpisode(params.id); } catch (error) { errorMessage = error instanceof Error ? error.message : 'Impossible de charger la grille.'; } finally { isLoading = false; } });
</script>
<main><a href={`/episodes/${params.id}`}>← Retour à l’épisode</a>{#if isLoading}<p>Chargement…</p>{:else if episode}<header><div><p>Épisode · {episode.title}</p><h1>Grille</h1><span>{gridLabel(episode)}</span></div><button onclick={() => isEditing = true}>{episode.metadata.grid_config ? 'Modifier la configuration' : 'Configurer la grille'}</button></header>{#if episode.metadata.grid_config}<section class="preview" aria-label="Aperçu de la grille">{#each Array(episode.metadata.grid_config.rows * episode.metadata.grid_config.columns) as _, index}<span>{index + 1}</span>{/each}</section><section class="details"><div><small>Cases vides</small><strong>{episode.metadata.grid_config.empty_cell_count}</strong></div>{#each Object.entries(episode.metadata.grid_config.point_distribution) as [points, count]}<div><small>{points} points</small><strong>{count} cases</strong></div>{/each}</section>{:else}<section class="empty"><h2>La grille n’est pas encore configurée</h2><p>Définissez ses dimensions et la répartition des points pour continuer.</p></section>{/if}{#if isEditing}<GridConfigurationDialog {episode} onclose={() => isEditing = false} onconfigured={(updated) => { episode = updated; isEditing = false; }} />{/if}{:else}<p class="error">{errorMessage}</p>{/if}</main>
<style>:global(*){box-sizing:border-box}:global(html),:global(body){margin:0;background:#0f172a;color:#f8fafc;font-family:Inter,ui-sans-serif,system-ui,sans-serif}main{width:min(100%,72rem);min-height:100dvh;margin:auto;padding:clamp(1.25rem,4vw,3rem)}a{color:#c4b5fd;font-size:.85rem;font-weight:750;text-decoration:none}header{display:flex;justify-content:space-between;gap:1rem;margin:3rem 0 2rem}header p,small{color:#94a3b8}h1{margin:.3rem 0;color:#f8fafc;font-size:clamp(2.5rem,6vw,4.5rem);letter-spacing:-.07em}header span{color:#cbd5e1}button{min-height:2.8rem;align-self:end;border:0;border-radius:.6rem;padding:.65rem 1rem;background:#7c3aed;color:white;cursor:pointer;font:inherit;font-weight:750}.preview{display:grid;grid-template-columns:repeat(auto-fit,minmax(4rem,1fr));gap:.5rem;border:1px solid #334155;border-radius:1rem;padding:1rem;background:#1e293b}.preview span{display:grid;min-height:4rem;place-items:center;border:1px solid #475569;border-radius:.55rem;background:#0f172a;color:#c4b5fd;font-weight:750}.details{display:flex;flex-wrap:wrap;gap:1rem;margin-top:1rem}.details div,.empty{border:1px solid #334155;border-radius:.75rem;padding:1rem;background:#1e293b}.details strong{display:block;margin-top:.35rem}.empty{margin-top:1rem}.empty p{color:#cbd5e1}.error{color:#fecaca}@media(max-width:600px){header{flex-direction:column}button{align-self:stretch}}</style>
