<script lang="ts">
	import { onMount } from 'svelte';
	import GridConfigurationDialog from '$lib/GridConfigurationDialog.svelte';
	import { getEpisode, gridLabel, type Episode } from '$lib/episodes-api';
	import type { PageProps } from './$types';
	let { params }: PageProps = $props(); let episode = $state<Episode | null>(null); let isLoading = $state(true); let isEditing = $state(false); let errorMessage = $state(''); let notice = $state('');
	onMount(async () => { try { episode = await getEpisode(params.id); } catch (error) { errorMessage = error instanceof Error ? error.message : 'Impossible de charger la grille.'; } finally { isLoading = false; } });
</script>
<main><a href={`/episodes/${params.id}`}>← Retour à l’épisode</a>{#if isLoading}<p>Chargement…</p>{:else if episode}<header><div><p>Épisode · {episode.title}</p><h1>Grille</h1><span>{gridLabel(episode)}</span></div><button onclick={() => isEditing = true}>{episode.metadata.grid_config ? 'Modifier la configuration' : 'Configurer la grille'}</button></header>{#if episode.metadata.grid_config}<section class="preview" style={`--columns:${episode.metadata.grid_config.columns}`} aria-label="Aperçu de la grille">{#each Array(episode.metadata.grid_config.rows * episode.metadata.grid_config.columns) as _, index}<span>{index + 1}</span>{/each}</section><section class="grid-actions" aria-label="Actions de la grille"><div><p class="eyebrow">Préparation</p><h2>Répartition de la grille</h2><p>Distribuez les contenus sur les cases configurées.</p></div><div><button type="button" onclick={() => notice = 'La répartition aléatoire des challenges sera disponible prochainement.'}>Répartir les challenges</button><button type="button" class="secondary" onclick={() => notice = 'L’affectation des lots sera disponible prochainement.'}>Affecter les lots</button></div></section>{#if notice}<p class="notice" role="status">{notice}</p>{/if}<section class="details"><div><small>Cases vides</small><strong>{episode.metadata.grid_config.empty_cell_count}</strong></div>{#each Object.entries(episode.metadata.grid_config.point_distribution) as [points, count]}<div><small>{points} points</small><strong>{count} cases</strong></div>{/each}</section>{:else}<section class="empty"><h2>La grille n’est pas encore configurée</h2><p>Définissez ses dimensions et la répartition des points pour continuer.</p></section>{/if}{#if isEditing}<GridConfigurationDialog {episode} onclose={() => isEditing = false} onconfigured={(updated) => { episode = updated; isEditing = false; }} />{/if}{:else}<p class="error">{errorMessage}</p>{/if}</main>
<style>:global(*){box-sizing:border-box}:global(html),:global(body){margin:0;background:#0f172a;color:#f8fafc;font-family:Inter,ui-sans-serif,system-ui,sans-serif}main{width:min(100%,72rem);min-height:100dvh;margin:auto;padding:clamp(1.25rem,4vw,3rem)}a{color:#c4b5fd;font-size:.85rem;font-weight:750;text-decoration:none}header{display:flex;justify-content:space-between;gap:1rem;margin:3rem 0 2rem}header p,small{color:#94a3b8}h1{margin:.3rem 0;color:#f8fafc;font-size:clamp(2.5rem,6vw,4.5rem);letter-spacing:-.07em}h2{margin:.25rem 0;color:#f8fafc;font-size:1.1rem}header span{color:#cbd5e1}button{min-height:2.8rem;align-self:end;border:0;border-radius:.6rem;padding:.65rem 1rem;background:#7c3aed;color:white;cursor:pointer;font:inherit;font-weight:750}.preview{display:grid;grid-template-columns:repeat(var(--columns),minmax(0,1fr));gap:.5rem;border:1px solid #334155;border-radius:1rem;padding:1rem;background:#1e293b}.preview span{display:grid;min-height:4rem;place-items:center;border:1px solid #475569;border-radius:.55rem;background:#0f172a;color:#c4b5fd;font-weight:750}.grid-actions{display:flex;align-items:center;justify-content:space-between;gap:1rem;margin-top:1rem;border:1px solid #334155;border-radius:.85rem;padding:1rem 1.2rem;background:#1e293b}.grid-actions p{margin:.35rem 0 0;color:#cbd5e1;font-size:.82rem}.eyebrow{margin:0!important;color:#c4b5fd!important;font-size:.68rem!important;font-weight:800;letter-spacing:.1em;text-transform:uppercase}.grid-actions>div:last-child{display:flex;gap:.6rem}.grid-actions .secondary{border:1px solid #475569;background:transparent;color:#ddd6fe}.notice{margin:1rem 0 0;border:1px solid rgba(56,189,248,.45);border-radius:.65rem;padding:.75rem 1rem;background:rgba(56,189,248,.08);color:#bae6fd;font-size:.82rem}.details{display:flex;flex-wrap:wrap;gap:1rem;margin-top:1rem}.details div,.empty{border:1px solid #334155;border-radius:.75rem;padding:1rem;background:#1e293b}.details strong{display:block;margin-top:.35rem}.empty{margin-top:1rem}.empty p{color:#cbd5e1}.error{color:#fecaca}@media(max-width:600px){header,.grid-actions{flex-direction:column;align-items:stretch}button{align-self:stretch}.grid-actions>div:last-child{flex-direction:column}.preview{gap:.3rem;padding:.5rem}.preview span{min-height:2.4rem;font-size:.72rem}}</style>
