# Generated by Django 6.0.8 on 2026-09-03 14:46

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_ping",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
