server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /200.html;
    }

    location /_app/immutable/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
