<script lang="ts">
	import { onMount } from 'svelte';
	import { ApiError, createParticipant, deactivateParticipant, getParticipants, type Episode, type Participant, type ParticipantRole } from '$lib/episodes-api';

	let { episode, onclose }: { episode: Episode; onclose: () => void } = $props();
	const roles: { value: ParticipantRole; label: string }[] = [{ value: 'PLAYER', label: 'Joueur' }, { value: 'PRESENTER', label: 'Présentateur' }, { value: 'OPERATOR', label: 'Opérateur' }, { value: 'SCREEN', label: 'Écran' }];
	let participants = $state<Participant[]>([]);
	let name = $state('');
	let role = $state<ParticipantRole>('PLAYER');
	let isLoading = $state(true);
	let isSaving = $state(false);
	let errorMessage = $state('');
	let nameInput: HTMLInputElement;

	function roleLabel(participantRole: ParticipantRole) { return roles.find((item) => item.value === participantRole)?.label ?? participantRole; }
	async function load() { try { participants = await getParticipants(episode.id); } catch (error) { errorMessage = error instanceof Error ? error.message : 'Impossible de charger les participants.'; } finally { isLoading = false; } }
	async function addParticipant() { errorMessage = ''; if (!name.trim()) { errorMessage = 'Indiquez le nom du participant.'; return; } isSaving = true; try { participants = [...participants, await createParticipant(episode.id, { name: name.trim(), role })]; name = ''; nameInput?.focus(); } catch (error) { errorMessage = error instanceof ApiError ? error.fieldErrors.name ?? error.message : 'Impossible d’ajouter ce participant.'; } finally { isSaving = false; } }
	async function removeParticipant(participant: Participant) { if (!confirm(`Désactiver ${participant.name} ?`)) return; errorMessage = ''; try { await deactivateParticipant(episode.id, participant.id); participants = participants.map((item) => item.id === participant.id ? { ...item, is_active: false } : item); } catch (error) { errorMessage = error instanceof Error ? error.message : 'Impossible de désactiver ce participant.'; } }
	onMount(() => { void load(); nameInput?.focus(); });
</script>

<div class="backdrop" role="presentation" onclick={(event) => event.currentTarget === event.target && !isSaving && onclose()}>
	<dialog class="dialog" open aria-labelledby="participants-title"><div class="heading"><div><p class="eyebrow">Équipe de session</p><h2 id="participants-title">Participants</h2></div><button class="close" type="button" aria-label="Fermer" onclick={onclose}>×</button></div><form onsubmit={(event) => { event.preventDefault(); void addParticipant(); }}><div class="add-row"><label for="participant-name">Nom<input bind:this={nameInput} id="participant-name" bind:value={name} disabled={isSaving} placeholder="Ex. Léon Kali" /></label><label for="participant-role">Rôle<select id="participant-role" bind:value={role} disabled={isSaving}>{#each roles as option}<option value={option.value}>{option.label}</option>{/each}</select></label><button type="submit" disabled={isSaving}>{isSaving ? 'Ajout…' : 'Ajouter'}</button></div></form>{#if errorMessage}<p class="error" role="alert">{errorMessage}</p>{/if}<section class="list" aria-label="Participants de l’épisode">{#if isLoading}<p class="empty" role="status">Chargement des participants…</p>{:else if participants.length}{#each participants as participant}<article class:inactive={!participant.is_active}><div><strong>{participant.name}</strong><span>{roleLabel(participant.role)} · @{participant.username}</span></div>{#if participant.is_active}<button type="button" onclick={() => void removeParticipant(participant)}>Désactiver</button>{:else}<em>Désactivé</em>{/if}</article>{/each}{:else}<p class="empty">Personne n’a encore été ajouté à cet épisode.</p>{/if}</section></dialog>
</div>

<style>
	.backdrop { position:fixed; z-index:20; inset:0; display:grid; place-items:center; padding:1rem; background:rgba(2,6,23,.7); backdrop-filter:blur(6px); }.dialog { width:min(100%,42rem); max-height:calc(100dvh - 2rem); overflow:auto; border:1px solid #475569; border-radius:1rem; padding:clamp(1.25rem,4vw,2rem); background:#1e293b; color:#f8fafc; box-shadow:0 1.5rem 5rem rgba(0,0,0,.42); }.heading { display:flex; justify-content:space-between; gap:1rem; }.eyebrow { margin:0 0 .45rem; color:#c4b5fd; font-size:.7rem; font-weight:800; letter-spacing:.12em; text-transform:uppercase; }.heading h2 { margin:0; font-size:1.55rem; letter-spacing:-.045em; }.close { width:2.75rem; height:2.75rem; border:1px solid #475569; border-radius:.65rem; background:transparent; color:#cbd5e1; cursor:pointer; font-size:1.6rem; }.add-row { display:grid; grid-template-columns:minmax(0,1fr) 9rem auto; gap:.7rem; align-items:end; margin:1.5rem 0 1rem; }.add-row label { color:#f8fafc; font-size:.78rem; font-weight:750; }.add-row input,.add-row select { width:100%; min-height:2.7rem; margin-top:.4rem; border:1px solid #475569; border-radius:.55rem; padding:0 .65rem; background:#0f172a; color:#f8fafc; font:inherit; }.add-row input:focus,.add-row select:focus { border-color:#a78bfa; outline:3px solid rgba(167,139,250,.24); }.add-row > button { min-height:2.7rem; border:0; border-radius:.55rem; padding:.6rem .85rem; background:#7c3aed; color:#fff; cursor:pointer; font:inherit; font-size:.8rem; font-weight:750; }.add-row > button:hover { background:#8b5cf6; }.add-row > button:disabled { cursor:not-allowed; opacity:.6; }.error { margin:.75rem 0; color:#fecaca; font-size:.82rem; }.list { border-top:1px solid #334155; }.list article { display:flex; align-items:center; justify-content:space-between; gap:1rem; border-bottom:1px solid #334155; padding:1rem 0; }.list strong,.list span { display:block; }.list strong { color:#f8fafc; font-size:.9rem; }.list span { margin-top:.25rem; color:#94a3b8; font-size:.75rem; }.list button { min-height:2.4rem; border:1px solid rgba(239,68,68,.55); border-radius:.5rem; padding:.45rem .65rem; background:transparent; color:#fca5a5; cursor:pointer; font:inherit; font-size:.75rem; font-weight:750; }.list button:hover { border-color:#ef4444; color:#fecaca; }.list article.inactive { opacity:.55; }.list em { color:#94a3b8; font-size:.75rem; font-style:normal; }.empty { margin:0; padding:2rem 0; color:#94a3b8; text-align:center; font-size:.85rem; }.close:focus-visible,.add-row button:focus-visible,.list button:focus-visible { outline:3px solid #a78bfa; outline-offset:3px; } @media (max-width:560px) { .add-row { grid-template-columns:1fr; }.add-row > button { width:100%; }.list article { align-items:flex-start; flex-direction:column; }.list button { width:100%; } }
</style>
